services:
  api:
    build: .
    depends_on:
      - db

  db:
    image: 'zcube/bitnami-compat-mongodb'
    ports:
      - 27017:27017
    restart: on-failure
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - ALLOW_EMPTY_PASSWORD=yes

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
